global using Ardalis.GuardClauses;
global using Ardalis.SmartEnum;
global using MediatR;
global using Playground.Domain.Entities.Aggregates.BuyerAggregate;
global using Playground.Domain.Entities.Aggregates.OrderAggregate;
global using Playground.Domain.SeedWork;
global using System;
global using System.Collections.Generic;
global using System.Linq;